#!/bin/bash

if [ "$1" ]; then
  ## determine path to app for includes
  APP_EXECUTION_PATH="$0"
  APP_EXECUTION_FILENAME="$(basename "$0")"
  APP_EXECUTION_ROOT="$(cd "$(dirname "$APP_EXECUTION_PATH")"; pwd)"
  APP_EXECUTION_PARENT_FOLDER="$(cd "$(dirname "$APP_EXECUTION_ROOT")"; pwd)"
  
  ## drop database
  mongo $1 --eval "db.dropDatabase()"

  ## delete content within tmp & dynamic content folders
  touch "$APP_EXECUTION_PARENT_FOLDER/tmp/_tmp"
  rm "$APP_EXECUTION_PARENT_FOLDER/tmp/"*
  touch "$APP_EXECUTION_PARENT_FOLDER/public/images/uploads/_tmp"
  rm "$APP_EXECUTION_PARENT_FOLDER/public/images/uploads/"*

  ## import collections from json files
  DATA_DIRECTORY="$APP_EXECUTION_ROOT/data"
  for filename in "$DATA_DIRECTORY"/*.json; do
    data_filename="$(basename "$filename")"
    data_collection_name="${data_filename%.*}"
    mongoimport --db $1 --collection $data_collection_name --file $filename
  done

  ## import images that are referenced by mongo docs
  for filename in "$DATA_DIRECTORY"/*.tar.gz; do
    data_filename="$(basename "$filename")"
    cd "$DATA_DIRECTORY"
    tar -xzvf "$data_filename"
    mv "$DATA_DIRECTORY/uploads/"* "$APP_EXECUTION_PARENT_FOLDER/public/images/uploads/"
    rm -rf "$DATA_DIRECTORY/uploads"
  done
else
  printf "NO DB SPECIFIED!!! Please execute this script with the name of the db you would like to seed as the first argument\n"
fi
