#!/bin/bash

if [ "$1" ]; then
  ## determine path to app for includes
  APP_EXECUTION_PATH="$0"
  APP_EXECUTION_FILENAME="$(basename "$0")"
  APP_EXECUTION_ROOT="$(cd "$(dirname "$APP_EXECUTION_PATH")"; pwd)"
  
  ## find and load json files
  DATA_DIRECTORY="$APP_EXECUTION_ROOT/data"
  for filename in "$DATA_DIRECTORY"/*.json; do
    data_filename="$(basename "$filename")"
    data_collection_name="${data_filename%.*}"
    mongoimport --db $1 --collection $data_collection_name --file $filename
  done
else
  printf "NO DB SPECIFIED!!! Please execute this script with the name of the db you would like to seed as the first argument\n"
fi


